<?php
/**
 * @category    OddBrew
 * @package     OddBrew_Exporter
 * @author      Alexandre Fayette <alexandre.fayette@gmail.com>
 * @link        https://github.com/OddBrew/ConfigExporter
 * @copyright   Copyright (c) 2016 Alexandre Fayette
 * @license     https://opensource.org/licenses/MIT  MIT License
 */

/** @var OddBrew_OddExporter_Block_Adminhtml_System_Config_Edit_Upload $this */
?>

<?php $helper = Mage::helper('oddbrew_oddexporter'); /** @var $helper OddBrew_OddExporter_Helper_Data */?>

<div class="oddexporter-upload-form standard">
    <form action="<?php echo $this->getFormAction() ?>" method="post">
        <label for="oddexporter-files"><?php echo $helper->__('Import config files :'); ?></label>
        <input id="oddexporter-files" name="files" type="file"  multiple>
        <input type="submit" class="form-button">
    </form>
</div>
